# flake8: noqa
"""Remove accepting_new column

Revision ID: 542d7aac3ede
Revises: 51e7e4ec8ef9
Create Date: 2022-10-18 21:18:27.549669

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '542d7aac3ede'
down_revision = '51e7e4ec8ef9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'accepting_new')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('accepting_new', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
