"""Fastapi tutorial

Revision ID: 5b3cdfb5d7d1
Revises: fb1bd8116844
Create Date: 2022-10-13 21:27:30.684838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b3cdfb5d7d1'
down_revision = 'fb1bd8116844'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
