# flake8: noqa
"""Refactor with cascade

Revision ID: 92bd2bcb9d67
Revises: 1ba081de97ba
Create Date: 2022-10-29 19:54:26.928463

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '92bd2bcb9d67'
down_revision = '1ba081de97ba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dnyf_groups',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(length=100), nullable=True),
    sa.Column('group_capacity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('group_id')
    )
    op.create_table('members',
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('member_id')
    )
    op.create_table('association_table',
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['dnyf_groups.group_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['members.member_id'], ondelete='CASCADE')
    )
    op.drop_index('ix_groups_id', table_name='groups')
    op.drop_index('ix_groups_name', table_name='groups')
    op.drop_table('groups')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('capacity', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_groups_name', 'groups', ['name'], unique=False)
    op.create_index('ix_groups_id', 'groups', ['id'], unique=False)
    op.drop_table('association_table')
    op.drop_table('members')
    op.drop_table('dnyf_groups')
    # ### end Alembic commands ###
